### ISSUE TITLE
ERRO[0000] Failed to get k8s client: no Auth Provider found for name "gcp"

### ISSUE THREAD

**Issue by outbounder** [omrikiei/ktunnel#10]
Hi @omrikiei and thank you for your work! 

I'm trying to use `ktunnel` but stumbled upon an issue which I'm posting here in case there are any clues on how to resolve :hammer: the showstopper :bug: :) (note: I'm golang newbie)

Here is what I can share so far of my findings:

# Steps to reproduce 

1. download [latest binary 1.1.7 for linux](https://github.com/omrikiei/ktunnel/releases/download/v1.1.7/ktunnel_1.1.7_Linux_x86_64.tar.gz)
2. execute with `ktunnel expose myapp 8084:8084 -n mynamespace`
3. see `ERRO[0000] Failed to get k8s client: no Auth Provider found for name "gcp"` 

## kubectl version

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.1", GitCommit:"d224476cd0730baca2b6e357d144171ed74192d6", GitTreeState:"clean", BuildDate:"2020-01-14T21:04:32Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-gke.12", GitCommit:"188432a69210ca32cafded81b4dd1c063720cac0", GitTreeState:"clean", BuildDate:"2019-11-07T19:27:01Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}
```

## kube config

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ...
    server: https://endpoint
  name: long_cluster_name
contexts:
- context:
    cluster: long_cluster_name
    user: long_cluster_name
  name: long_cluster_name
current-context: long_cluster_name
kind: Config
preferences: {}
users:
- name: xyz
  user:
    auth-provider:
      config:
        access-token: XYZ
        cmd-args: config config-helper --format=json
        cmd-path: /usr/lib/google-cloud-sdk/bin/gcloud
        expiry: "UTC-DATE"
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
```
