### ISSUE TITLE
ktunnel expose --ca-file option not used?

### ISSUE THREAD

**Issue by caedo960** [omrikiei/ktunnel#70]
Hi,

First of all thank you so much for creating this awesome project 👍

I'm trying to enable TLS using `--tls` and `--ca-file` options but I'm not sure is it actually working. What I'm curious about is this part:

https://github.com/omrikiei/ktunnel/blob/6bf63db523c81a9e06dfe2fd44607af910551e30/cmd/expose.go#L114

Should the `CertFile` parameter be `CaFile` instead?

https://github.com/omrikiei/ktunnel/blob/6bf63db523c81a9e06dfe2fd44607af910551e30/cmd/expose.go#L127

**Comment by omrikiei** [comment]
Good catch, will address this shortly

**Comment by caedo960** [comment]
Hi, any updates regarding this?

**Comment by omrikiei** [comment]
Hi @caedo960,
I've release v1.4.5 which fixed the instrumentation of tls on all subcommands - please note that for this to work with expose/inject you will need to bake a ktunnel image that contains the tls certificate and key file and use both `--cert` and `--key` in the client command (inject/expose)

after thinking about it a little, I'm want to develop a mutual tls connection without the need to pass certificates and keys around.. do you think an enclose mTLS would be better for your use case?

**Comment by caedo960** [comment]
Thank you for the fixes. I've ran into a few problems:

- For some reason `brew` does not offer the 1.4.6 version yet (1.4.4 is the latest).
- I pulled the latest changes from master and edited the dockerfile to include `server-cert.pem` and `server-key.pem` files and build the image, but when I ran command `ktunnel expose -n test -s tcp -t --cert server-cert.pem --key server-key.pem --server-image <CUSTOM_KTUNNEL_IMAGE> test 8080` the pod fails with an error: `error executing command error="unknown flag: --key server-key.pem"`.

Other thing is that if I look at the failing pod's YAML file what ktunnel has created the `args` does not contain `--cert` argument at all 

```yaml
spec:                                                                                                                                                                                                                                                                                                                                                                  
 automountServiceAccountToken: false                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
 containers:
  - args:                                                                                                                                                                                                                                                                                                                                                              
    - server                                                                                                                                                                                                                                                                                                                                                           
    - -p                                                                                                                                                                                                                                                                                                                                                               
    - "28688"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
    - --key server-key.pem
```
